### PR TITLE
use latest version of `actions/checkout` in README example

### PR DESCRIPTION
**Pull request by coliff**
Use latest version of `actions/checkout` in README example

### CODE REVIEW

**Comment by dbmeneses** [comment]
Thanks for the PR. Do you know what is the functional impact of upgrading from v2 to v3?

**Comment by coliff** [comment]
yep, the Changelog is here: https://github.com/actions/checkout/releases

**Comment by dbmeneses** [comment]
@coliff I meant how does it impact this action. For example, is there a specific reason you opened this PR? Anything that the action will benefit from?

**Comment by coliff** [comment]
I think it's mainly for running Node 16 by default. Node 12 has been out of support since [April 2022](https://github.com/nodejs/Release/#end-of-life-releases).
REF: https://discourse.julialang.org/t/node-js-12-actions-deprecation-warning-on-github/88718

**Review by dbmeneses — APPROVED** [review]

**Comment by dbmeneses** [comment]
thanks!

**Pull request merged**
